Repository Xenotrix-Technologies/Xenotune-Development, pull requests merged in 2025-07, with the labels that each got.

#28 update config.json
  config.json
Labels: updation

#29 generate music without Bass
  __pycache__/main.cpython-313.pyc
  __pycache__/music_gen.cpython-313.pyc
  config.json
  main.py
  music_gen.py
  output/focus_composition_20250703_112103.mid
  output/sleep_composition_20250702_154910.mid
  templates/index.html
Labels: features

#30 change some keys in config.json and change codes
  __pycache__/main.cpython-313.pyc
  __pycache__/music_gen.cpython-313.pyc
  config.json
  main.py
  music_gen.py
  output/focus_composition_20250703_112103.mid
  output/sleep_composition_20250703_141029.mid
  requirements.txt
  templates/index.html
Labels: updation

#34 update code fith FluidR3_GM.sf2
  __pycache__/main.cpython-313.pyc
  __pycache__/music_gen.cpython-313.pyc
  main.py
  music_gen.py
  output/focus_composition_20250703_195129.mid
  output/sleep_composition_20250703_144747.mid
  requirements.txt
Labels: updation

#38 add ffprobe.exe using LFS
  .gitattributes
  ffmpeg/LICENSE
  ffmpeg/README.txt
  ffmpeg/bin/ffprobe.exe
  ffmpeg/doc/bootstrap.min.css
  ffmpeg/doc/community.html
  ffmpeg/doc/default.css
  ffmpeg/doc/developer.html
  ffmpeg/doc/faq.html
  ffmpeg/doc/fate.html
  ffmpeg/doc/ffmpeg-all.html
  ffmpeg/doc/ffmpeg-bitstream-filters.html
  ffmpeg/doc/ffmpeg-codecs.html
  ffmpeg/doc/ffmpeg-devices.html
  ffmpeg/doc/ffmpeg-filters.html
  ffmpeg/doc/ffmpeg-formats.html
  ffmpeg/doc/ffmpeg-protocols.html
  ffmpeg/doc/ffmpeg-resampler.html
  ffmpeg/doc/ffmpeg-scaler.html
  ffmpeg/doc/ffmpeg-utils.html
  ffmpeg/doc/ffmpeg.html
  ffmpeg/doc/ffplay-all.html
  ffmpeg/doc/ffplay.html
  ffmpeg/doc/ffprobe-all.html
  ffmpeg/doc/ffprobe.html
  ffmpeg/doc/general.html
  ffmpeg/doc/git-howto.html
  ffmpeg/doc/libavcodec.html
  ffmpeg/doc/libavdevice.html
  ffmpeg/doc/libavfilter.html
  ffmpeg/doc/libavformat.html
  ffmpeg/doc/libavutil.html
  ffmpeg/doc/libswresample.html
  ffmpeg/doc/libswscale.html
  ffmpeg/doc/mailing-list-faq.html
  ffmpeg/doc/nut.html
  ffmpeg/doc/platform.html
  ffmpeg/doc/style.min.css
  ffmpeg/presets/libvpx-1080p.ffpreset
  ffmpeg/presets/libvpx-1080p50_60.ffpreset
  ffmpeg/presets/libvpx-360p.ffpreset
  ffmpeg/presets/libvpx-720p.ffpreset
  ffmpeg/presets/libvpx-720p50_60.ffpreset
Labels: updation

#42 Implement code changes to enhance functionality and improve performance
  __pycache__/music_gen.cpython-313.pyc
  music_gen.py
  output/relax_composition_20250707_211605.mid
  output/sleep_composition_20250707_230439.mid
  output/sleep_composition_20250707_230439_mixed.mp3
Labels: updation

#43 update config.json and udjest music_volume
  __pycache__/music_gen.cpython-313.pyc
  config.json
  music_gen.py
  output/sleep_composition_20250707_230439.mid
  output/sleep_composition_20250707_230439_mixed.mp3
  output/sleep_composition_20250708_174411.mid
  output/sleep_composition_20250708_174411_mixed.mp3
Labels: updation

#44 Update requirements and remove unused output files and added ai_note_gen.py
  __pycache__/ai_note_gen.cpython-311.pyc
  __pycache__/music_gen.cpython-311.pyc
  ai_note_gen.py
  music_gen.py
  output/focus_composition_20250708_195548.mid
  output/focus_composition_20250708_195556.mid
  requirements.txt
Labels: wontfix

#46 Add .gitignore file to exclude unnecessary files and directories
  .gitignore
Labels: updation

#47 Update requirements.txt to remove unused dependencies and update existing ones
  requirements.txt
Labels: updation

#49 Remove index.html template from the project
  templates/index.html
Labels: updation

#50 Refactor music generation and playback system
  __pycache__/main.cpython-311.pyc
  __pycache__/music_gen.cpython-311.pyc
  ai_note_gen.py
  config.json
  main.py
  music_gen.py
  requirements.txt
Labels: updation

#51 Enhance music generation and playback: add cleanup functionality
  __pycache__/main.cpython-313.pyc
  __pycache__/music_gen.cpython-313.pyc
  music_gen.py
  output/focus_130934.mid
  output/focus_132029.mid
  output/focus_132033.mid
  output/focus_132203.mid
  output/focus_composition_20250708_195548.mid
  output/focus_composition_20250708_195556.mid
  output/sleep_composition_20250708_174411.mid
  output/sleep_composition_20250708_174411_mixed.mp3
Labels: updation

#53 Refactor music generation output and update return values in JSON gen
  __pycache__/music_gen.cpython-311.pyc
  config.json
  json_gen.py
  music_gen.py
  output/focus_composition_20250714_181758.mid
  output/focus_composition_20250714_181758_mixed.mp3
  output/relax.mid
  output/relax_mixed.mp3
Labels: updation

#54 Refactor code structure for improved readability and maintainability
  __pycache__/main.cpython-311.pyc
  __pycache__/music_gen.cpython-311.pyc
  config.json
  music_gen.py
  output/relax.mid
  output/relax_mixed.mp3
  output/sleep.mid
  output/sleep_mixed.mp3
  requirements.txt
Labels: updation

#55 Update requirements.txt to add and modify package dependencies
  requirements.txt
Labels: updation

#59 Update compiled Python bytecode for music_gen module
  __pycache__/music_gen.cpython-311.pyc
  config.json
  music_gen.py
  static/music/relax_20250716_232345_mixed.mp3
Labels: updation

#64 Update music generation API and modify configuration for improved music playback
  __pycache__/main.cpython-313.pyc
  config.json
  main.py
  output/music.mid
  output/music_mixed.mp3
Labels: updation

#65 remove .gitattributes
  .gitattributes
Labels: updation

#66 Refactor Firebase initialization and improve error handling; update music generation API to support dynamic modes
  __pycache__/main.cpython-313.pyc
  __pycache__/music_gen.cpython-313.pyc
  config.json
  firebase.py
  json_gen.py
  main.py
  music_gen.py
  output/music.mid
  output/music_mixed.mp3
Labels: updation

#67 Update Firebase credentials and improve error handling in music generation API
  assets/serviceAccountKey.json
  firebase.py
  main.py
  music_gen.py
Labels: updation

#68 Refactor code structure for improved readability and maintainability
  __pycache__/main.cpython-313.pyc
  __pycache__/music_gen.cpython-313.pyc
  config.json
  main.py
  music_gen.py
  output/music.mid
  output/music_mixed.mp3
  relax.mid
  relax_mixed.mp3
Labels: updation

#69 Refactor music request handling to improve validation and structure
  main.py
Labels: updation

#74 update full code and remove backend playback with store song directly in cloud database
  __pycache__/main.cpython-313.pyc
  __pycache__/music_gen.cpython-313.pyc
  config.json
  main.py
  music_gen.py
  relax.mid
  relax_mixed.mp3
Labels: updation

#75 Refactor code structure for improved readability and maintainability and stop playback and store music direct to cloud
  .gitignore
  __pycache__/main.cpython-313.pyc
  __pycache__/music_gen.cpython-313.pyc
  assets/serviceAccountKey.json
  main.py
  music_gen.py
Labels: updation

#78 Master
  __pycache__/main.cpython-313.pyc
  firebase.py
  main.py
Labels: updation

#81 bucket name changed
  firebase.py
Labels: updation
